### ISSUE TITLE
Executing Truffle tests hangs without output

### ISSUE THREAD

**Issue by kiview** [internet-sicherheit/proof-of-visit-dapp#2]
When executing the Truffle tests from the Truffle project dir with
```bash
proof-of-visit-dapp/truffle$ truffle test
```
the execution just hangs, without any output. 

Was running this on Ubuntu 20.04 with NPM 6.14.4. What is the expected output? What should actually happen?

Truffle docs say:
```
* Networks define how you connect to your ethereum client and let you set the
* defaults web3 uses to send transactions. If you don't specify one truffle
* will spin up a development blockchain for you on port 9545 when you
* run `develop` or `test`. You can ask a truffle command to use a specific
```
so I would expect a local network to pop up.

**Comment by kiview** [comment]
@marius1909 
So we need a running Ganach network, then everything works, correct?

**Comment by marius1909** [comment]
Not necessarily. This is what it says on the Truffle website

> While Truffle Develop is an all-in-one personal blockchain and console, you can also use Ganache, a desktop application, to launch your personal blockchain. Ganache can be a more easy-to-understand tool for those new to Ethereum and the blockchain, as it displays much more information up-front.

I will shift my focus onto testing again tomorrow.

**Comment by kiview** [comment]
Yeah, I was just wondering, since the default values did not work without Ganache. Maybe we did something wrong here, let's close this and say, atm Ganache is necessary.
