### ISSUE TITLE
Testing Communication between Android and Ethereum

### ISSUE THREAD

**Issue by cekaya** [internet-sicherheit/proof-of-visit-dapp#8]
Build a simple Application that adds one to a number and gives the current sum.

**Comment by cekaya** [comment]
I created a new branch called "example_android_studio" for this issue

**Comment by cekaya** [comment]
String file = "C:\\Users\\Cennet\\Master\\ArbeitBlockchain\\DAPPS\\Wallets\\UTC--2020-04-15T11-41-09.546146800Z--40983af4978c7d83ea7d9f74e27dae2957183aaf.json";
 
Credentials credentials = WalletUtils.loadCredentials("Hallo1234", file);
__________________________________________________________________________________________________________
W/System.err: java.io.FileNotFoundException: C:\Users\Cennet\Master\ArbeitBlockchain\DAPPS\Wallets\UTC--2020-04-15T11-41-09.546146800Z--40983af4978c7d83ea7d9f74e27dae2957183aaf.json: open failed: ENOENT (No such file or directory)
__________________________________________________________________________________________________________
I don't know where the problem is. The file is correct.

**Comment by kiview** [comment]
In a Java file path, you should always use forward slashes `/`. They are platform-independent and could be related to this.

Also sometimes you have to use small drive letter `c` instead of `C`. Not 100% sure, but I assume it has to do with Windows file path in the end.

**Comment by cekaya** [comment]
Nice thanks. The error is fixed with "Users/Cennet/Master/ArbeitBlockchain/..."

With IntelliJ it worked also with the previous path. Strange.

**Comment by cekaya** [comment]
Update: I tried many options but it does not work. The same problem is still there. 
With IntelliJ it works with the path. Strange.

**Comment by cekaya** [comment]
The current error message is: 
`java.security.NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC.`

Normally I can solve this problem with the setupBouncyCastle()  method. (I found this information in google and I checked  Dominiks code, he used this method too)
After adding this my debugger gets stuck in the try block and does nothing (its loading endlessly).

**Comment by kiview** [comment]
ECDSA is probably an eliptic curve algorithm, which indeed, should be provided by BouncyCastle. However, I have zero experience about how to specify such BouncyCastle dependencies on Android.

Debugger getting stuck sounds strange, considering that without a debugger, Android is thrown an exception. Where did you put the breakpoint? Look into the implementation of `setupBouncyCastle()` and try to find out, where it fails there.

Did you see this comment?
https://github.com/web3j/web3j/issues/915#issuecomment-483145928

**Comment by cekaya** [comment]
Yes I already used this comment. Unbelievable how long the debbuging needs since then.

**Comment by kiview** [comment]
Did you also see this SO discussion https://stackoverflow.com/questions/55123228/java-security-nosuchalgorithmexception-no-such-algorithm-ecdsa-for-provider-bc? Seems highly related.
Did @girzzly get this working on Android? Might depend on Android SDK version, or if emulator or physical device is used. Please sort this out together.

**Comment by girzzly** [comment]
I will discuss this issue with @cekaya.
